### ISSUE TITLE
addSupportInfo.sqf Port/Implementation

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#40]
**Module: Briefing**

- [x] Get name, seats, pylon/turret info.
- [x] Sort by Eden subcategories (APC, Tanks, Truck, Jet, etc).
- [x] Port from old framework.
- [x] Frontend (see below)

Port and finish the [addSupportInfo.sqf](https://github.com/Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR/blob/ff914a40aa3197e0da54be90c8e9a39def903c98/sia_f/briefing/addSupportInfo.sqf) from the SIA Mission Framework.

The purpose of this script is to autogenerate all the logistical information that should go in the support tab.

Ideally, it would take an array of vehicle objects and generate text containing each vehicle's number of seats, pylons, ammo count, and ACE cargo space.

Frontend Ideas:
- Have an input section in briefing settings for an array of vehicle classnames.
- Add an attribute checkbox for vehicles to "Add to Vehicle Info".

~~The text would then be injected into the Support tab of the briefing.~~

**Comment by SiegeToaster** [comment]
Make sure you port over all of the necessary functions from the mission framework to sia3f before actually closing btw.

**Comment by SiegeToaster** [comment]
For the front end, I'm thinking we add a checkbox to all possible support vehicles/objects that says something like "Add to Support Info".  There will likely be some overlap with what objects this is added to because we have to make it compatible with **all** vehicles, emplacements (for artillery), and drones, that means adding anything with a 'brain', which might cause some overlap with unintended units.  See [Attributes: Condition](https://community.bistudio.com/wiki/Eden_Editor:_Configuring_Attributes#Condition).  Right now I'm thinking something like ``(objectBrain AND NOT objectControllable) OR (objectVehicle AND objectSimulated)`` (pseudocode).

**Comment by L-McKendrick** [comment]
#75 (former task 2) moved to its own issue
