### ISSUE TITLE
Respawn support and customization

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#59]
Currently, the framework makes no modifications to the respawn settings, other than an extension creating a description.ext file and setting `respawnOnStart = -1`. 

The framework should automatically set up proper respawn settings, while allowing for customization of respawn templates if desired.
The [cfgAttributes wiki states that description.ext items *should* be able to be modified via 3den attributes](https://community.bistudio.com/wiki/Eden_Editor:_Configuring_Attributes#Scenario), so this should all be theoretically possible and even quite simple.

With how arma config hierarchy works, it may be easier overide to just modify the default values of the options in Settings > Multiplayer.

A way for the GM to determine respawn positions is also needed, as well as the backend for it. The old template used simple Logics from the template that could be placed, and then moved the [respawn markers](https://github.com/Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR/blob/cddfdaccca16e0f99cf76b839805be0cacda4e8d/sia_f/core/initServer.sqf#L69-L73) to them.

For reference, see [missionInfo.hpp](https://github.com/Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR/blob/14b2d8b27a7c51eb0eddd28dd934e8dff1c064fd/%23%20MISSION%20CONFIG/missionInfo.hpp#L1-L14) and [description.ext](https://github.com/Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR/blob/14b2d8b27a7c51eb0eddd28dd934e8dff1c064fd/description.ext#L69-L70)

- [x] Respawn templates customization via new cfgAttribute (optional) OR overwrite vanilla 3den defaults.
- [x] Respawn delay via new cfgAttribute (optional)
- [x] `respawn = 3` via cfgAttributes OR overwrite vanilla 3den default.
- [x] `respawnOnStart = -1` via new cfgAttribute (done via extension).
- [ ] Respawn positions

**Comment by SiegeToaster** [comment]
> The [cfgAttributes wiki states that description.ext items should be able to be modified via 3den attributes](https://community.bistudio.com/wiki/Eden_Editor:_Configuring_Attributes#Scenario), so this should all be theoretically possible and even quite simple.
The editable entries are listed [here](https://community.bistudio.com/wiki/Eden_Editor:_Setting_Attributes#Scenario).  respawnOnStart is not editable through eden commands.

**Comment by SiegeToaster** [comment]
I think that respawn tickets and respawn delay should be left to the GM since they are not required for functionality.  I also believe that the ``respawn`` cfgAttribute needs to be set to 3 ([see wiki](https://community.bistudio.com/wiki/Arma_3:_Respawn#Respawn_Types)).  If there is a way to edit the default values through a ***config***, not a script, then that would be desirable and the respawn delay can be thrown in as 15 seconds or something.

As far as respawn positions work, the respawn module works with the spectator framework.  As the [ACE Spectator Framework wiki](https://ace3.acemod.org/wiki/framework/spectator-framework.html) says, the only restriction is the respawn templates:
> It's worth noting that templates "MenuPosition" and "MenuInventory" are not currently compatible with the "ace_spectator" template.

So, as far as the respawn templates go, we could automatically set ``"ace_spectator"`` to the templates, but the rest should be up to the GM, including tickets.

**Comment by L-McKendrick** [comment]
[Replying to this comment.](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/issues/59#issuecomment-1258257130)

I agree with the points regarding respawn tickets and respawn delay. The respawn cfgAttribute can be done through config, possibly by simply overwriting the default value used by 3den (Make "Respawn on Custom Position" the default) and maybe remove the other options.

> As the [ACE Spectator Framework wiki](https://ace3.acemod.org/wiki/framework/spectator-framework.html) says, the only restriction is the respawn templates: ...
(Yeah that's what I said in [discord](https://discord.com/channels/689674061366034435/966070504060489788/1023823779916419072) in reference to the "End Game Respawn Menu")

**Comment by SiegeToaster** [comment]
edited comment to remove tickets and change ``respawn = 1`` to ``respawn = 3``
