### ISSUE TITLE
Add "Enable Framework" checkbox option

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#65]
Concept:

Basically a checkbox at the top of the "SIA Framework Settings" that says "Enable Framework". Unchecked by default, when this box is not ticked, then none of the framework runs.

This allows those who have the mod loaded but aren't making an SIA mission to have this mod loaded without having to frustratingly deal with the scripts when messing around in the editor.

If too much work for the Alpha release, this should definitely be done by the public release.

**Comment by SiegeToaster** [comment]
Could also be done by only enabling scripts and such when the "Initialize
Framework" button is pressed.

**Comment by L-McKendrick** [comment]
Could also potentially replace the "initialize framework" tab.

**Comment by SiegeToaster** [comment]
Making the initialize framework button a checkbox would make things pretty complicated and would require a new extension to delete description.ext.  Extension would be fairly complicated due to having to check the file contents to ensure that nothing the user wrote is being overwritten, which *could* cause memory/CPU usage problems if the file is incredibly large.

All in all, putting in functionality to enable and disable the framework at whim would be quite involved, to start off we'd have to do a complete audit of all of the variables that are set to the mission.sqm file so that they could all be removed.  Then, if someone accidentally disables the framework they lose all of their stuff.  imo the button can serve the same purpose (allowing a GM to make a mission without the mod interfering) while being much easier to implement, I also see no reason why you'd enable and then disable the famework.

**Comment by SiegeToaster** [comment]
Should be able to use the ``GET_CONFIG`` macro to check the ``frameworkInit`` hidden value.  Need to check if that can also be used in 3DEN (configuration module).
